name: Building and testing
# Build and test job

on:
  #push
  
  
permissions:
  actions: read
  checks: read
  statuses: read
  contents: write
  packages: read
 
jobs:
  build_job:
    uses: ./.github/workflows/build.yml

  test_job:
    needs: build_job
    uses: ./.github/workflows/tests.yml