name: Run Test Runner

on:
  push:
    branches:
      - main  # 每次向 main 分支推送时触发

jobs:
  run_tests:
    runs-on: windows-latest  # 运行环境为 Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 拉取完整仓库，避免部分文件缺失

      - name: Print working directory
        run: pwd  # 确保我们在正确的目录下

      - name: List all files (debugging)
        run: dir /s  # 在 Windows runner 上列出所有文件，检查 requirements.txt 是否存在

      - name: Install dependencies
        run: python -m pip install -r .github/workflows/requirements.txt  # 确保路径正确

      - name: Run test runner
        run: python assignment/integrationtests/testrunner.py  # 运行测试脚本
