name: Run Test Runner

on:
  push:
    branches:
      - main  # 每次向 main 分支推送时触发

jobs:
  run_tests:
    runs-on: windows-latest  # 使用 Windows 环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 选择所需的 Python 版本

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # 安装依赖项（如果有）check

      - name: Run test runner
        run: |
          python C:\Users\xue6szh\Documents\Personal\Python\QAassignment\assignment\integrationtests\testrunner.py