name: Run Test Runner

on:
  push:
    branches:
      - main  # 每次向 main 分支推送时触发

jobs:
  run_tests:
    runs-on: windows-latest  # 运行环境为 Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print working directory
        run: pwd  # 打印当前工作目录

      - name: List files for debugging
        run: |
          Get-ChildItem -Recurse  # 列出所有文件，确认路径

      - name: Run runner.exe
        run: .github/workflows/runner.exe  # 运行 runner.exe

      - name: Run testrunner.py
        run: python .github/workflows/testrunner.py  # 运行 testrunner.py