name: Run Test Runner

on:
  push:
    branches:
      - main  # 每次向 main 分支推送时触发

jobs:
  run_tests:
    runs-on: windows-latest  # 运行环境为 Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 拉取完整仓库，避免部分文件缺失

      - name: Print working directory
        run: Get-Location  # PowerShell 中使用 Get-Location 打印当前工作目录

      - name: List files (debugging)
        run: |
          Get-ChildItem -Recurse  # 在 PowerShell 中递归列出所有文件，查看文件是否存在

      # - name: Install dependencies
      #   run: python -m pip install -r requirements.txt  # 确保路径正确，这里假设 requirements.txt 在项目根目录下

      - name: Run test runner
        run: python assignment/integrationtests/testrunner.py  # 运行测试脚本
