name: Run Test Runner

on:
  push:
    branches:
      - main  # 每次向 main 分支推送时触发

jobs:
  run_tests:
    runs-on: windows-latest  # 运行环境为 Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 拉取完整仓库，避免部分文件缺失

      - name: Print working directory
        run: |
          Get-Location  # 打印当前工作目录

      - name: List files (debugging)
        run: |
          Get-ChildItem -Recurse  # 在 PowerShell 中递归列出所有文件，确保文件存在

      - name: Run test runner with relative path
        run: python assignment/integrationtests/testrunner.py  # 使用相对路径来访问
